### ISSUE TITLE
[BUG] action v2 has no effect on the cloud

### ISSUE THREAD

**Issue by erhosen** [Goodsmileduck/yandex-serverless-action#35]
Hi there!
I appreciate your work; it helps me run a lot of lambdas and works like a charm!

However, yandex-serverless-action@v2 doesn't seem to work. 

This is my action:
```yaml
      - uses: goodsmileduck/yandex-serverless-action@v2
        with:
          token: ${{ secrets.YC_TOKEN }}
          function_id: ${{ secrets.YC_FUNCTION_ID }}
          service_account: ${{ secrets.YC_SERVICE_ACCOUNT }}
          bucket: ${{ secrets.YC_BUCKET }}
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          runtime: 'python311'
          memory: '1024'
          execution_timeout: '15'
          entrypoint: 'ycloud.handler'
          environment: VAR1=${{ secrets.VAR1 }},VAR2=${{ secrets.VAR2 }},VAR3=${{ secrets.VAR3 }}
          source: 'app'
```

This is **success** log of execution (**in 2 seconds**):
```
Run goodsmileduck/yandex-serverless-action@v2
  with:
    token: ***
    function_id: ***
    service_account: ***
    bucket: ***
    accessKeyId: ***
    secretAccessKey: ***
    runtime: python311
    memory: 1024
    execution_timeout: 15
    entrypoint: ycloud.handler
    environment: VAR1=***,VAR2=***,VAR3=***
    source: app
Function inputs set
::group::ZipDirectory
ZipDirectory
  Archive initialize
  Source ignore pattern: "[]"
```

When I looked at the developer console, **I saw no new version of lambda deployed. I didn't see any new archive in Object Storage either.** 

But if I change **v2** to **v1** - it works as expected. Here is the success log (**31 seconds**):
```
Warning: Unexpected input(s) 'accessKeyId', 'secretAccessKey', valid inputs are ['description', 'token', 'function_id', 'bucket', 'runtime', 'entrypoint', 'source', 'exclude', 'memory', 'environment', 'execution_timeout', 'service_account']
Run goodsmileduck/yandex-serverless-action@v1
Function inputs set
::group::ZipDirectory
ZipDirectory
Buffer size: 59809425b
Upload to bucket: "***/***/***.zip"
::group::Get function by ID: "***"
Get function by ID: "***"
::group::Create function version
Create function version
::set-output name=time::09:54:35 GMT+0000 (Coordinated Universal Time)
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I know that it's not the best bug description, but that's all I have. It's not a blocker for me as well - I continue using v1 and it's cover 100% of my requirements.
