### ISSUE TITLE
Error INVALID_ARGUMENT: Исходный архив не является валидным ZIP архивом

### ISSUE THREAD

**Issue by kostyavelikiyi** [Goodsmileduck/yandex-serverless-action#37]
Не получается задеплоить функцию на go

Ошибка из YC 

`INVALID_ARGUMENT: Исходный архив не является валидным ZIP архивом` 

Yml файл

```
name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v2
        with:
          token: ${{ secrets.TOKEN }}
          function_id: "***"
          runtime: "golang121"
          entrypoint: "index.Handler"
          exclude: "main.go"
          environment: YDB_METADATA_CREDENTIALS=1
```

Файл логов github action

[logs_10.zip](https://github.com/Goodsmileduck/yandex-serverless-action/files/13628086/logs_10.zip)
